/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/channels/oem/macbook-draco.glb -o src/components/channel-visuals/Macbook3DModel.tsx -t 
*/

// Removed React import
import { useGLTF } from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber'


import type { SiteMode } from "../../data/liveContent";


function MacbookLight({ nodes }: { nodes: any }) {
  return (
        <group position={[0, 0, 0]}>
        <group position={[0, 1.09, -10.34]} rotation={[-1.885, 0, 0]}>
          <group position={[0, 0.23, 10.7]}>
            <mesh geometry={nodes.mesh_116.geometry} material={nodes.mesh_116.material} />
            <mesh geometry={nodes.mesh_116_1.geometry} material={nodes.mesh_116_1.material} />
          </group>
          <mesh geometry={nodes.mesh_117.geometry} material={nodes.mesh_117.material} position={[0, -0.008, 10.7]} />
          <mesh geometry={nodes.mesh_118.geometry} material={nodes.mesh_118.material} position={[0, -0.022, 11.08]} />
          <mesh geometry={nodes.mesh_119.geometry} material={nodes.mesh_119.material} position={[0, -0.052, 10.7]} />
          <mesh geometry={nodes.mesh_120.geometry} material={nodes.mesh_120.material} position={[0, -0.034, 20.685]} />
          <mesh geometry={nodes.mesh_121.geometry} material={nodes.mesh_121.material} position={[0, -0.042, 20.465]} />
          <mesh geometry={nodes.mesh_122.geometry} material={nodes.mesh_122.material} position={[0, -0.03, 0.63]} />
          <mesh geometry={nodes.mesh_123.geometry} material={nodes.mesh_123.material} position={[0, 0.464, 10.7]} />
        </group>
        <group position={[0, 0.545, 0]}>
          <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
          <mesh geometry={nodes.mesh_0_1.geometry} material={nodes.mesh_0_1.material} />
        </group>
        <mesh geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} position={[0, 0.99, -4.165]} />
        <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} position={[0, 0.96, 6.26]} />
        <mesh geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} position={[0, 0.15, -4.165]} />
        <mesh geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} position={[0, 0.15, 6.26]} />
        <group position={[0, 0.14, 0]}>
          <mesh geometry={nodes.mesh_5.geometry} material={nodes.mesh_5.material} />
          <mesh geometry={nodes.mesh_5_1.geometry} material={nodes.mesh_5_1.material} />
        </group>
        <mesh geometry={nodes.mesh_6.geometry} material={nodes.mesh_6.material} position={[0, -0.014, 0]} />
        <mesh geometry={nodes.mesh_7.geometry} material={nodes.mesh_7.material} position={[-13.43, -0.09, -9.36]} />
        <mesh geometry={nodes.mesh_8.geometry} material={nodes.mesh_8.material} position={[-13.43, -0.09, 9.36]} />
        <mesh geometry={nodes.mesh_9.geometry} material={nodes.mesh_9.material} position={[13.43, -0.09, -9.36]} />
        <mesh geometry={nodes.mesh_10.geometry} material={nodes.mesh_10.material} position={[13.43, -0.09, 9.36]} />
        <mesh geometry={nodes.mesh_11.geometry} material={nodes.mesh_11.material} position={[-12.397, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_12.geometry} material={nodes.mesh_12.material} position={[-12.397, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_13_instance_0.geometry} material={nodes.mesh_13_instance_0.material} position={[-10.094, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_13_instance_1.geometry} material={nodes.mesh_13_instance_1.material} position={[-8.241, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_13_instance_2.geometry} material={nodes.mesh_13_instance_2.material} position={[-6.389, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_13_instance_3.geometry} material={nodes.mesh_13_instance_3.material} position={[-4.536, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_13_instance_4.geometry} material={nodes.mesh_13_instance_4.material} position={[-2.684, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_13_instance_5.geometry} material={nodes.mesh_13_instance_5.material} position={[-0.831, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_13_instance_6.geometry} material={nodes.mesh_13_instance_6.material} position={[1.021, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_13_instance_7.geometry} material={nodes.mesh_13_instance_7.material} position={[2.874, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_13_instance_8.geometry} material={nodes.mesh_13_instance_8.material} position={[4.726, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_13_instance_9.geometry} material={nodes.mesh_13_instance_9.material} position={[6.579, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_13_instance_10.geometry} material={nodes.mesh_13_instance_10.material} position={[8.431, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_13_instance_11.geometry} material={nodes.mesh_13_instance_11.material} position={[10.284, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_14.geometry} material={nodes.mesh_14.material} position={[-10.094, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_15.geometry} material={nodes.mesh_15.material} position={[-8.241, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_16.geometry} material={nodes.mesh_16.material} position={[-6.389, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_17.geometry} material={nodes.mesh_17.material} position={[-4.536, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_18.geometry} material={nodes.mesh_18.material} position={[-2.684, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_19.geometry} material={nodes.mesh_19.material} position={[-0.831, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_20.geometry} material={nodes.mesh_20.material} position={[1.021, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_21.geometry} material={nodes.mesh_21.material} position={[2.874, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_22.geometry} material={nodes.mesh_22.material} position={[4.726, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_23.geometry} material={nodes.mesh_23.material} position={[6.579, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_24.geometry} material={nodes.mesh_24.material} position={[8.431, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_25.geometry} material={nodes.mesh_25.material} position={[10.284, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_26.geometry} material={nodes.mesh_26.material} position={[12.492, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_27.geometry} material={nodes.mesh_27.material} position={[12.492, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_28_instance_0.geometry} material={nodes.mesh_28_instance_0.material} position={[-12.825, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_28_instance_1.geometry} material={nodes.mesh_28_instance_1.material} position={[-10.925, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_28_instance_2.geometry} material={nodes.mesh_28_instance_2.material} position={[-9.025, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_28_instance_3.geometry} material={nodes.mesh_28_instance_3.material} position={[-7.125, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_28_instance_4.geometry} material={nodes.mesh_28_instance_4.material} position={[-5.225, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_28_instance_5.geometry} material={nodes.mesh_28_instance_5.material} position={[-3.325, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_28_instance_6.geometry} material={nodes.mesh_28_instance_6.material} position={[-1.425, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_28_instance_7.geometry} material={nodes.mesh_28_instance_7.material} position={[0.475, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_28_instance_8.geometry} material={nodes.mesh_28_instance_8.material} position={[2.375, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_28_instance_9.geometry} material={nodes.mesh_28_instance_9.material} position={[4.275, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_28_instance_10.geometry} material={nodes.mesh_28_instance_10.material} position={[6.175, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_28_instance_11.geometry} material={nodes.mesh_28_instance_11.material} position={[8.075, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_28_instance_12.geometry} material={nodes.mesh_28_instance_12.material} position={[9.975, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_28_instance_13.geometry} material={nodes.mesh_28_instance_13.material} position={[-9.975, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_28_instance_14.geometry} material={nodes.mesh_28_instance_14.material} position={[-8.075, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_28_instance_15.geometry} material={nodes.mesh_28_instance_15.material} position={[-6.175, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_28_instance_16.geometry} material={nodes.mesh_28_instance_16.material} position={[-4.275, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_28_instance_17.geometry} material={nodes.mesh_28_instance_17.material} position={[-2.375, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_28_instance_18.geometry} material={nodes.mesh_28_instance_18.material} position={[-0.475, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_28_instance_19.geometry} material={nodes.mesh_28_instance_19.material} position={[1.425, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_28_instance_20.geometry} material={nodes.mesh_28_instance_20.material} position={[3.325, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_28_instance_21.geometry} material={nodes.mesh_28_instance_21.material} position={[5.225, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_28_instance_22.geometry} material={nodes.mesh_28_instance_22.material} position={[7.125, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_28_instance_23.geometry} material={nodes.mesh_28_instance_23.material} position={[9.025, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_28_instance_24.geometry} material={nodes.mesh_28_instance_24.material} position={[10.925, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_28_instance_25.geometry} material={nodes.mesh_28_instance_25.material} position={[12.825, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_28_instance_26.geometry} material={nodes.mesh_28_instance_26.material} position={[-9.5, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_28_instance_27.geometry} material={nodes.mesh_28_instance_27.material} position={[-7.6, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_28_instance_28.geometry} material={nodes.mesh_28_instance_28.material} position={[-5.7, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_28_instance_29.geometry} material={nodes.mesh_28_instance_29.material} position={[-3.8, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_28_instance_30.geometry} material={nodes.mesh_28_instance_30.material} position={[-1.9, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_28_instance_31.geometry} material={nodes.mesh_28_instance_31.material} position={[0, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_28_instance_32.geometry} material={nodes.mesh_28_instance_32.material} position={[1.9, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_28_instance_33.geometry} material={nodes.mesh_28_instance_33.material} position={[3.8, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_28_instance_34.geometry} material={nodes.mesh_28_instance_34.material} position={[5.7, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_28_instance_35.geometry} material={nodes.mesh_28_instance_35.material} position={[7.6, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_28_instance_36.geometry} material={nodes.mesh_28_instance_36.material} position={[9.5, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_28_instance_37.geometry} material={nodes.mesh_28_instance_37.material} position={[-8.55, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_28_instance_38.geometry} material={nodes.mesh_28_instance_38.material} position={[-6.65, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_28_instance_39.geometry} material={nodes.mesh_28_instance_39.material} position={[-4.75, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_28_instance_40.geometry} material={nodes.mesh_28_instance_40.material} position={[-2.85, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_28_instance_41.geometry} material={nodes.mesh_28_instance_41.material} position={[-0.95, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_28_instance_42.geometry} material={nodes.mesh_28_instance_42.material} position={[0.95, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_28_instance_43.geometry} material={nodes.mesh_28_instance_43.material} position={[2.85, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_28_instance_44.geometry} material={nodes.mesh_28_instance_44.material} position={[4.75, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_28_instance_45.geometry} material={nodes.mesh_28_instance_45.material} position={[6.65, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_28_instance_46.geometry} material={nodes.mesh_28_instance_46.material} position={[8.55, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_28_instance_47.geometry} material={nodes.mesh_28_instance_47.material} position={[-12.825, 1.063, 0.585]} />
        <mesh geometry={nodes.mesh_28_instance_48.geometry} material={nodes.mesh_28_instance_48.material} position={[-10.925, 1.063, 0.585]} />
        <mesh geometry={nodes.mesh_28_instance_49.geometry} material={nodes.mesh_28_instance_49.material} position={[-9.025, 1.063, 0.585]} />
        <mesh geometry={nodes.mesh_28_instance_50.geometry} material={nodes.mesh_28_instance_50.material} position={[7.125, 1.063, 0.585]} />
        <mesh geometry={nodes.mesh_28_instance_51.geometry} material={nodes.mesh_28_instance_51.material} position={[9.025, 1.063, 0.585]} />
        <mesh geometry={nodes.mesh_28_instance_52.geometry} material={nodes.mesh_28_instance_52.material} position={[12.825, 1.063, 0.585]} />
        <mesh geometry={nodes.mesh_29.geometry} material={nodes.mesh_29.material} position={[-12.825, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_30.geometry} material={nodes.mesh_30.material} position={[-10.925, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_31.geometry} material={nodes.mesh_31.material} position={[-9.025, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_32.geometry} material={nodes.mesh_32.material} position={[-7.125, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_33.geometry} material={nodes.mesh_33.material} position={[-5.225, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_34.geometry} material={nodes.mesh_34.material} position={[-3.325, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_35.geometry} material={nodes.mesh_35.material} position={[-1.425, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_36.geometry} material={nodes.mesh_36.material} position={[0.475, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_37.geometry} material={nodes.mesh_37.material} position={[2.375, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_38.geometry} material={nodes.mesh_38.material} position={[4.275, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_39.geometry} material={nodes.mesh_39.material} position={[6.175, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_40.geometry} material={nodes.mesh_40.material} position={[8.075, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_41.geometry} material={nodes.mesh_41.material} position={[9.975, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_42_instance_0.geometry} material={nodes.mesh_42_instance_0.material} position={[12.35, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_42_instance_1.geometry} material={nodes.mesh_42_instance_1.material} position={[-12.35, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_43.geometry} material={nodes.mesh_43.material} position={[12.35, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_44.geometry} material={nodes.mesh_44.material} position={[-12.35, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_45.geometry} material={nodes.mesh_45.material} position={[-9.975, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_46.geometry} material={nodes.mesh_46.material} position={[-8.075, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_47.geometry} material={nodes.mesh_47.material} position={[-6.175, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_48.geometry} material={nodes.mesh_48.material} position={[-4.275, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_49.geometry} material={nodes.mesh_49.material} position={[-2.375, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_50.geometry} material={nodes.mesh_50.material} position={[-0.475, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_51.geometry} material={nodes.mesh_51.material} position={[1.425, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_52.geometry} material={nodes.mesh_52.material} position={[3.325, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_53.geometry} material={nodes.mesh_53.material} position={[5.225, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_54.geometry} material={nodes.mesh_54.material} position={[7.125, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_55.geometry} material={nodes.mesh_55.material} position={[9.025, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_56.geometry} material={nodes.mesh_56.material} position={[10.925, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_57.geometry} material={nodes.mesh_57.material} position={[12.825, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_58_instance_0.geometry} material={nodes.mesh_58_instance_0.material} position={[-12.112, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_58_instance_1.geometry} material={nodes.mesh_58_instance_1.material} position={[12.113, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_59.geometry} material={nodes.mesh_59.material} position={[-12.112, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_60.geometry} material={nodes.mesh_60.material} position={[-9.5, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_61.geometry} material={nodes.mesh_61.material} position={[-7.6, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_62.geometry} material={nodes.mesh_62.material} position={[-5.7, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_63.geometry} material={nodes.mesh_63.material} position={[-3.8, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_64.geometry} material={nodes.mesh_64.material} position={[-1.9, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_65.geometry} material={nodes.mesh_65.material} position={[0, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_66.geometry} material={nodes.mesh_66.material} position={[1.9, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_67.geometry} material={nodes.mesh_67.material} position={[3.8, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_68.geometry} material={nodes.mesh_68.material} position={[5.7, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_69.geometry} material={nodes.mesh_69.material} position={[7.6, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_70.geometry} material={nodes.mesh_70.material} position={[9.5, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_71.geometry} material={nodes.mesh_71.material} position={[12.113, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_72_instance_0.geometry} material={nodes.mesh_72_instance_0.material} position={[-11.637, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_72_instance_1.geometry} material={nodes.mesh_72_instance_1.material} position={[11.637, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_73.geometry} material={nodes.mesh_73.material} position={[-11.637, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_74.geometry} material={nodes.mesh_74.material} position={[-8.55, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_75.geometry} material={nodes.mesh_75.material} position={[-6.65, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_76.geometry} material={nodes.mesh_76.material} position={[-4.75, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_77.geometry} material={nodes.mesh_77.material} position={[-2.85, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_78.geometry} material={nodes.mesh_78.material} position={[-0.95, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_79.geometry} material={nodes.mesh_79.material} position={[0.95, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_80.geometry} material={nodes.mesh_80.material} position={[2.85, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_81.geometry} material={nodes.mesh_81.material} position={[4.75, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_82.geometry} material={nodes.mesh_82.material} position={[6.65, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_83.geometry} material={nodes.mesh_83.material} position={[8.55, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_84.geometry} material={nodes.mesh_84.material} position={[11.637, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_85.geometry} material={nodes.mesh_85.material} position={[-12.825, 1.132, 0.585]} />
        <mesh geometry={nodes.mesh_86.geometry} material={nodes.mesh_86.material} position={[-10.925, 1.132, 0.585]} />
        <mesh geometry={nodes.mesh_87.geometry} material={nodes.mesh_87.material} position={[-9.025, 1.132, 0.585]} />
        <mesh geometry={nodes.mesh_88_instance_0.geometry} material={nodes.mesh_88_instance_0.material} position={[-6.887, 1.063, 0.585]} />
        <mesh geometry={nodes.mesh_88_instance_1.geometry} material={nodes.mesh_88_instance_1.material} position={[4.988, 1.063, 0.585]} />
        <mesh geometry={nodes.mesh_89.geometry} material={nodes.mesh_89.material} position={[-6.887, 1.132, 0.585]} />
        <mesh geometry={nodes.mesh_90.geometry} material={nodes.mesh_90.material} position={[-0.95, 1.063, 0.585]} />
        <mesh geometry={nodes.mesh_91.geometry} material={nodes.mesh_91.material} position={[4.988, 1.132, 0.585]} />
        <mesh geometry={nodes.mesh_92.geometry} material={nodes.mesh_92.material} position={[7.125, 1.132, 0.585]} />
        <mesh geometry={nodes.mesh_93.geometry} material={nodes.mesh_93.material} position={[9.025, 1.132, 0.585]} />
        <mesh geometry={nodes.mesh_94_instance_0.geometry} material={nodes.mesh_94_instance_0.material} position={[10.925, 1.063, 0.11]} />
        <mesh geometry={nodes.mesh_94_instance_1.geometry} material={nodes.mesh_94_instance_1.material} position={[10.925, 1.063, 1.06]} />
        <mesh geometry={nodes.mesh_95.geometry} material={nodes.mesh_95.material} position={[10.925, 1.132, 0.11]} />
        <mesh geometry={nodes.mesh_96.geometry} material={nodes.mesh_96.material} position={[10.925, 1.132, 1.06]} />
        <mesh geometry={nodes.mesh_97.geometry} material={nodes.mesh_97.material} position={[12.825, 1.132, 0.585]} />
        <mesh geometry={nodes.mesh_98.geometry} material={nodes.mesh_98.material} position={[0, 1.078, 6.26]} />
        <mesh geometry={nodes.mesh_99.geometry} material={nodes.mesh_99.material} position={[-14.775, 1.094, -4.165]} />
        <mesh geometry={nodes.mesh_100.geometry} material={nodes.mesh_100.material} position={[14.775, 1.094, -4.165]} />
        <mesh geometry={nodes.mesh_101.geometry} material={nodes.mesh_101.material} position={[-15.634, 0.545, -6.6]} />
        <mesh geometry={nodes.mesh_102.geometry} material={nodes.mesh_102.material} position={[-15.638, 0.545, -6.6]} />
        <mesh geometry={nodes.mesh_103.geometry} material={nodes.mesh_103.material} position={[-15.634, 0.545, -4.3]} />
        <mesh geometry={nodes.mesh_104.geometry} material={nodes.mesh_104.material} position={[-15.638, 0.545, -4.3]} />
        <mesh geometry={nodes.mesh_105.geometry} material={nodes.mesh_105.material} position={[-15.634, 0.545, -2.1]} />
        <mesh geometry={nodes.mesh_106.geometry} material={nodes.mesh_106.material} position={[-15.638, 0.545, -2.1]} />
        <mesh geometry={nodes.mesh_107.geometry} material={nodes.mesh_107.material} position={[-15.634, 0.545, 3.9]} />
        <mesh geometry={nodes.mesh_108.geometry} material={nodes.mesh_108.material} position={[-15.638, 0.545, 3.9]} />
        <mesh geometry={nodes.mesh_109.geometry} material={nodes.mesh_109.material} position={[15.634, 0.545, -5.9]} />
        <mesh geometry={nodes.mesh_110.geometry} material={nodes.mesh_110.material} position={[15.638, 0.545, -5.9]} />
        <mesh geometry={nodes.mesh_111.geometry} material={nodes.mesh_111.material} position={[15.634, 0.545, -3.1]} />
        <mesh geometry={nodes.mesh_112.geometry} material={nodes.mesh_112.material} position={[15.638, 0.545, -3.1]} />
        <mesh geometry={nodes.mesh_113.geometry} material={nodes.mesh_113.material} position={[15.634, 0.545, -0.6]} />
        <mesh geometry={nodes.mesh_114.geometry} material={nodes.mesh_114.material} position={[15.638, 0.545, -0.6]} />
        <mesh geometry={nodes.mesh_115.geometry} material={nodes.mesh_115.material} position={[0, 0.62, 11.49]} />
        <mesh geometry={nodes.mesh_124.geometry} material={nodes.mesh_124.material} position={[0, 1.32, -10.67]} />
        <group position={[-12.98, 1.32, -10.67]}>
          <mesh geometry={nodes.mesh_125.geometry} material={nodes.mesh_125.material} />
          <mesh geometry={nodes.mesh_125_1.geometry} material={nodes.mesh_125_1.material} />
        </group>
        <group position={[12.98, 1.32, -10.67]}>
          <mesh geometry={nodes.mesh_126.geometry} material={nodes.mesh_126.material} />
          <mesh geometry={nodes.mesh_126_1.geometry} material={nodes.mesh_126_1.material} />
        </group>
        <mesh geometry={nodes.mesh_127.geometry} material={nodes.mesh_127.material} position={[-7.7, 1.32, -11.034]} />
        <mesh geometry={nodes.mesh_128.geometry} material={nodes.mesh_128.material} position={[7.7, 1.32, -11.034]} />
      </group>
  );
}

function MacbookDark({ nodes }: { nodes: any }) {
  return (
        <group position={[0, 0, 0]}>
        <group position={[0, 1.09, -10.34]} rotation={[-1.885, 0, 0]}>
          <group position={[0, 0.23, 10.7]}>
            <mesh geometry={nodes.mesh_245.geometry} material={nodes.mesh_245.material} />
            <mesh geometry={nodes.mesh_245_1.geometry} material={nodes.mesh_245_1.material} />
          </group>
          <mesh geometry={nodes.mesh_246.geometry} material={nodes.mesh_246.material} position={[0, -0.008, 10.7]} />
          <mesh geometry={nodes.mesh_247.geometry} material={nodes.mesh_247.material} position={[0, -0.022, 11.08]} />
          <mesh geometry={nodes.mesh_248.geometry} material={nodes.mesh_248.material} position={[0, -0.052, 10.7]} />
          <mesh geometry={nodes.mesh_249.geometry} material={nodes.mesh_249.material} position={[0, -0.034, 20.685]} />
          <mesh geometry={nodes.mesh_250.geometry} material={nodes.mesh_250.material} position={[0, -0.042, 20.465]} />
          <mesh geometry={nodes.mesh_251.geometry} material={nodes.mesh_251.material} position={[0, -0.03, 0.63]} />
          <mesh geometry={nodes.mesh_252.geometry} material={nodes.mesh_252.material} position={[0, 0.464, 10.7]} />
        </group>
        <group position={[0, 0.545, 0]}>
          <mesh geometry={nodes.mesh_129.geometry} material={nodes.mesh_129.material} />
          <mesh geometry={nodes.mesh_129_1.geometry} material={nodes.mesh_129_1.material} />
        </group>
        <mesh geometry={nodes.mesh_130.geometry} material={nodes.mesh_130.material} position={[0, 0.99, -4.165]} />
        <mesh geometry={nodes.mesh_131.geometry} material={nodes.mesh_131.material} position={[0, 0.96, 6.26]} />
        <mesh geometry={nodes.mesh_132.geometry} material={nodes.mesh_132.material} position={[0, 0.15, -4.165]} />
        <mesh geometry={nodes.mesh_133.geometry} material={nodes.mesh_133.material} position={[0, 0.15, 6.26]} />
        <group position={[0, 0.14, 0]}>
          <mesh geometry={nodes.mesh_134.geometry} material={nodes.mesh_134.material} />
          <mesh geometry={nodes.mesh_134_1.geometry} material={nodes.mesh_134_1.material} />
        </group>
        <mesh geometry={nodes.mesh_135.geometry} material={nodes.mesh_135.material} position={[0, -0.014, 0]} />
        <mesh geometry={nodes.mesh_136.geometry} material={nodes.mesh_136.material} position={[-13.43, -0.09, -9.36]} />
        <mesh geometry={nodes.mesh_137.geometry} material={nodes.mesh_137.material} position={[-13.43, -0.09, 9.36]} />
        <mesh geometry={nodes.mesh_138.geometry} material={nodes.mesh_138.material} position={[13.43, -0.09, -9.36]} />
        <mesh geometry={nodes.mesh_139.geometry} material={nodes.mesh_139.material} position={[13.43, -0.09, 9.36]} />
        <mesh geometry={nodes.mesh_140.geometry} material={nodes.mesh_140.material} position={[-12.397, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_141.geometry} material={nodes.mesh_141.material} position={[-12.397, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_142_instance_0.geometry} material={nodes.mesh_142_instance_0.material} position={[-10.094, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_142_instance_1.geometry} material={nodes.mesh_142_instance_1.material} position={[-8.241, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_142_instance_2.geometry} material={nodes.mesh_142_instance_2.material} position={[-6.389, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_142_instance_3.geometry} material={nodes.mesh_142_instance_3.material} position={[-4.536, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_142_instance_4.geometry} material={nodes.mesh_142_instance_4.material} position={[-2.684, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_142_instance_5.geometry} material={nodes.mesh_142_instance_5.material} position={[-0.831, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_142_instance_6.geometry} material={nodes.mesh_142_instance_6.material} position={[1.021, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_142_instance_7.geometry} material={nodes.mesh_142_instance_7.material} position={[2.874, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_142_instance_8.geometry} material={nodes.mesh_142_instance_8.material} position={[4.726, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_142_instance_9.geometry} material={nodes.mesh_142_instance_9.material} position={[6.579, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_142_instance_10.geometry} material={nodes.mesh_142_instance_10.material} position={[8.431, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_142_instance_11.geometry} material={nodes.mesh_142_instance_11.material} position={[10.284, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_143.geometry} material={nodes.mesh_143.material} position={[-10.094, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_144.geometry} material={nodes.mesh_144.material} position={[-8.241, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_145.geometry} material={nodes.mesh_145.material} position={[-6.389, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_146.geometry} material={nodes.mesh_146.material} position={[-4.536, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_147.geometry} material={nodes.mesh_147.material} position={[-2.684, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_148.geometry} material={nodes.mesh_148.material} position={[-0.831, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_149.geometry} material={nodes.mesh_149.material} position={[1.021, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_150.geometry} material={nodes.mesh_150.material} position={[2.874, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_151.geometry} material={nodes.mesh_151.material} position={[4.726, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_152.geometry} material={nodes.mesh_152.material} position={[6.579, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_153.geometry} material={nodes.mesh_153.material} position={[8.431, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_154.geometry} material={nodes.mesh_154.material} position={[10.284, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_155.geometry} material={nodes.mesh_155.material} position={[12.492, 1.063, -8.915]} />
        <mesh geometry={nodes.mesh_156.geometry} material={nodes.mesh_156.material} position={[12.492, 1.132, -8.915]} />
        <mesh geometry={nodes.mesh_157_instance_0.geometry} material={nodes.mesh_157_instance_0.material} position={[-12.825, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_157_instance_1.geometry} material={nodes.mesh_157_instance_1.material} position={[-10.925, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_157_instance_2.geometry} material={nodes.mesh_157_instance_2.material} position={[-9.025, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_157_instance_3.geometry} material={nodes.mesh_157_instance_3.material} position={[-7.125, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_157_instance_4.geometry} material={nodes.mesh_157_instance_4.material} position={[-5.225, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_157_instance_5.geometry} material={nodes.mesh_157_instance_5.material} position={[-3.325, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_157_instance_6.geometry} material={nodes.mesh_157_instance_6.material} position={[-1.425, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_157_instance_7.geometry} material={nodes.mesh_157_instance_7.material} position={[0.475, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_157_instance_8.geometry} material={nodes.mesh_157_instance_8.material} position={[2.375, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_157_instance_9.geometry} material={nodes.mesh_157_instance_9.material} position={[4.275, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_157_instance_10.geometry} material={nodes.mesh_157_instance_10.material} position={[6.175, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_157_instance_11.geometry} material={nodes.mesh_157_instance_11.material} position={[8.075, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_157_instance_12.geometry} material={nodes.mesh_157_instance_12.material} position={[9.975, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_157_instance_13.geometry} material={nodes.mesh_157_instance_13.material} position={[-9.975, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_157_instance_14.geometry} material={nodes.mesh_157_instance_14.material} position={[-8.075, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_157_instance_15.geometry} material={nodes.mesh_157_instance_15.material} position={[-6.175, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_157_instance_16.geometry} material={nodes.mesh_157_instance_16.material} position={[-4.275, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_157_instance_17.geometry} material={nodes.mesh_157_instance_17.material} position={[-2.375, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_157_instance_18.geometry} material={nodes.mesh_157_instance_18.material} position={[-0.475, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_157_instance_19.geometry} material={nodes.mesh_157_instance_19.material} position={[1.425, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_157_instance_20.geometry} material={nodes.mesh_157_instance_20.material} position={[3.325, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_157_instance_21.geometry} material={nodes.mesh_157_instance_21.material} position={[5.225, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_157_instance_22.geometry} material={nodes.mesh_157_instance_22.material} position={[7.125, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_157_instance_23.geometry} material={nodes.mesh_157_instance_23.material} position={[9.025, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_157_instance_24.geometry} material={nodes.mesh_157_instance_24.material} position={[10.925, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_157_instance_25.geometry} material={nodes.mesh_157_instance_25.material} position={[12.825, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_157_instance_26.geometry} material={nodes.mesh_157_instance_26.material} position={[-9.5, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_157_instance_27.geometry} material={nodes.mesh_157_instance_27.material} position={[-7.6, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_157_instance_28.geometry} material={nodes.mesh_157_instance_28.material} position={[-5.7, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_157_instance_29.geometry} material={nodes.mesh_157_instance_29.material} position={[-3.8, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_157_instance_30.geometry} material={nodes.mesh_157_instance_30.material} position={[-1.9, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_157_instance_31.geometry} material={nodes.mesh_157_instance_31.material} position={[0, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_157_instance_32.geometry} material={nodes.mesh_157_instance_32.material} position={[1.9, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_157_instance_33.geometry} material={nodes.mesh_157_instance_33.material} position={[3.8, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_157_instance_34.geometry} material={nodes.mesh_157_instance_34.material} position={[5.7, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_157_instance_35.geometry} material={nodes.mesh_157_instance_35.material} position={[7.6, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_157_instance_36.geometry} material={nodes.mesh_157_instance_36.material} position={[9.5, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_157_instance_37.geometry} material={nodes.mesh_157_instance_37.material} position={[-8.55, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_157_instance_38.geometry} material={nodes.mesh_157_instance_38.material} position={[-6.65, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_157_instance_39.geometry} material={nodes.mesh_157_instance_39.material} position={[-4.75, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_157_instance_40.geometry} material={nodes.mesh_157_instance_40.material} position={[-2.85, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_157_instance_41.geometry} material={nodes.mesh_157_instance_41.material} position={[-0.95, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_157_instance_42.geometry} material={nodes.mesh_157_instance_42.material} position={[0.95, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_157_instance_43.geometry} material={nodes.mesh_157_instance_43.material} position={[2.85, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_157_instance_44.geometry} material={nodes.mesh_157_instance_44.material} position={[4.75, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_157_instance_45.geometry} material={nodes.mesh_157_instance_45.material} position={[6.65, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_157_instance_46.geometry} material={nodes.mesh_157_instance_46.material} position={[8.55, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_157_instance_47.geometry} material={nodes.mesh_157_instance_47.material} position={[-12.825, 1.063, 0.585]} />
        <mesh geometry={nodes.mesh_157_instance_48.geometry} material={nodes.mesh_157_instance_48.material} position={[-10.925, 1.063, 0.585]} />
        <mesh geometry={nodes.mesh_157_instance_49.geometry} material={nodes.mesh_157_instance_49.material} position={[-9.025, 1.063, 0.585]} />
        <mesh geometry={nodes.mesh_157_instance_50.geometry} material={nodes.mesh_157_instance_50.material} position={[7.125, 1.063, 0.585]} />
        <mesh geometry={nodes.mesh_157_instance_51.geometry} material={nodes.mesh_157_instance_51.material} position={[9.025, 1.063, 0.585]} />
        <mesh geometry={nodes.mesh_157_instance_52.geometry} material={nodes.mesh_157_instance_52.material} position={[12.825, 1.063, 0.585]} />
        <mesh geometry={nodes.mesh_158.geometry} material={nodes.mesh_158.material} position={[-12.825, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_159.geometry} material={nodes.mesh_159.material} position={[-10.925, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_160.geometry} material={nodes.mesh_160.material} position={[-9.025, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_161.geometry} material={nodes.mesh_161.material} position={[-7.125, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_162.geometry} material={nodes.mesh_162.material} position={[-5.225, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_163.geometry} material={nodes.mesh_163.material} position={[-3.325, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_164.geometry} material={nodes.mesh_164.material} position={[-1.425, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_165.geometry} material={nodes.mesh_165.material} position={[0.475, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_166.geometry} material={nodes.mesh_166.material} position={[2.375, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_167.geometry} material={nodes.mesh_167.material} position={[4.275, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_168.geometry} material={nodes.mesh_168.material} position={[6.175, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_169.geometry} material={nodes.mesh_169.material} position={[8.075, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_170.geometry} material={nodes.mesh_170.material} position={[9.975, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_171_instance_0.geometry} material={nodes.mesh_171_instance_0.material} position={[12.35, 1.063, -7.015]} />
        <mesh geometry={nodes.mesh_171_instance_1.geometry} material={nodes.mesh_171_instance_1.material} position={[-12.35, 1.063, -5.115]} />
        <mesh geometry={nodes.mesh_172.geometry} material={nodes.mesh_172.material} position={[12.35, 1.132, -7.015]} />
        <mesh geometry={nodes.mesh_173.geometry} material={nodes.mesh_173.material} position={[-12.35, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_174.geometry} material={nodes.mesh_174.material} position={[-9.975, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_175.geometry} material={nodes.mesh_175.material} position={[-8.075, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_176.geometry} material={nodes.mesh_176.material} position={[-6.175, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_177.geometry} material={nodes.mesh_177.material} position={[-4.275, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_178.geometry} material={nodes.mesh_178.material} position={[-2.375, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_179.geometry} material={nodes.mesh_179.material} position={[-0.475, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_180.geometry} material={nodes.mesh_180.material} position={[1.425, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_181.geometry} material={nodes.mesh_181.material} position={[3.325, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_182.geometry} material={nodes.mesh_182.material} position={[5.225, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_183.geometry} material={nodes.mesh_183.material} position={[7.125, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_184.geometry} material={nodes.mesh_184.material} position={[9.025, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_185.geometry} material={nodes.mesh_185.material} position={[10.925, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_186.geometry} material={nodes.mesh_186.material} position={[12.825, 1.132, -5.115]} />
        <mesh geometry={nodes.mesh_187_instance_0.geometry} material={nodes.mesh_187_instance_0.material} position={[-12.112, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_187_instance_1.geometry} material={nodes.mesh_187_instance_1.material} position={[12.113, 1.063, -3.215]} />
        <mesh geometry={nodes.mesh_188.geometry} material={nodes.mesh_188.material} position={[-12.112, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_189.geometry} material={nodes.mesh_189.material} position={[-9.5, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_190.geometry} material={nodes.mesh_190.material} position={[-7.6, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_191.geometry} material={nodes.mesh_191.material} position={[-5.7, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_192.geometry} material={nodes.mesh_192.material} position={[-3.8, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_193.geometry} material={nodes.mesh_193.material} position={[-1.9, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_194.geometry} material={nodes.mesh_194.material} position={[0, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_195.geometry} material={nodes.mesh_195.material} position={[1.9, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_196.geometry} material={nodes.mesh_196.material} position={[3.8, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_197.geometry} material={nodes.mesh_197.material} position={[5.7, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_198.geometry} material={nodes.mesh_198.material} position={[7.6, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_199.geometry} material={nodes.mesh_199.material} position={[9.5, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_200.geometry} material={nodes.mesh_200.material} position={[12.113, 1.132, -3.215]} />
        <mesh geometry={nodes.mesh_201_instance_0.geometry} material={nodes.mesh_201_instance_0.material} position={[-11.637, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_201_instance_1.geometry} material={nodes.mesh_201_instance_1.material} position={[11.637, 1.063, -1.315]} />
        <mesh geometry={nodes.mesh_202.geometry} material={nodes.mesh_202.material} position={[-11.637, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_203.geometry} material={nodes.mesh_203.material} position={[-8.55, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_204.geometry} material={nodes.mesh_204.material} position={[-6.65, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_205.geometry} material={nodes.mesh_205.material} position={[-4.75, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_206.geometry} material={nodes.mesh_206.material} position={[-2.85, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_207.geometry} material={nodes.mesh_207.material} position={[-0.95, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_208.geometry} material={nodes.mesh_208.material} position={[0.95, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_209.geometry} material={nodes.mesh_209.material} position={[2.85, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_210.geometry} material={nodes.mesh_210.material} position={[4.75, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_211.geometry} material={nodes.mesh_211.material} position={[6.65, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_212.geometry} material={nodes.mesh_212.material} position={[8.55, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_213.geometry} material={nodes.mesh_213.material} position={[11.637, 1.132, -1.315]} />
        <mesh geometry={nodes.mesh_214.geometry} material={nodes.mesh_214.material} position={[-12.825, 1.132, 0.585]} />
        <mesh geometry={nodes.mesh_215.geometry} material={nodes.mesh_215.material} position={[-10.925, 1.132, 0.585]} />
        <mesh geometry={nodes.mesh_216.geometry} material={nodes.mesh_216.material} position={[-9.025, 1.132, 0.585]} />
        <mesh geometry={nodes.mesh_217_instance_0.geometry} material={nodes.mesh_217_instance_0.material} position={[-6.887, 1.063, 0.585]} />
        <mesh geometry={nodes.mesh_217_instance_1.geometry} material={nodes.mesh_217_instance_1.material} position={[4.988, 1.063, 0.585]} />
        <mesh geometry={nodes.mesh_218.geometry} material={nodes.mesh_218.material} position={[-6.887, 1.132, 0.585]} />
        <mesh geometry={nodes.mesh_219.geometry} material={nodes.mesh_219.material} position={[-0.95, 1.063, 0.585]} />
        <mesh geometry={nodes.mesh_220.geometry} material={nodes.mesh_220.material} position={[4.988, 1.132, 0.585]} />
        <mesh geometry={nodes.mesh_221.geometry} material={nodes.mesh_221.material} position={[7.125, 1.132, 0.585]} />
        <mesh geometry={nodes.mesh_222.geometry} material={nodes.mesh_222.material} position={[9.025, 1.132, 0.585]} />
        <mesh geometry={nodes.mesh_223_instance_0.geometry} material={nodes.mesh_223_instance_0.material} position={[10.925, 1.063, 0.11]} />
        <mesh geometry={nodes.mesh_223_instance_1.geometry} material={nodes.mesh_223_instance_1.material} position={[10.925, 1.063, 1.06]} />
        <mesh geometry={nodes.mesh_224.geometry} material={nodes.mesh_224.material} position={[10.925, 1.132, 0.11]} />
        <mesh geometry={nodes.mesh_225.geometry} material={nodes.mesh_225.material} position={[10.925, 1.132, 1.06]} />
        <mesh geometry={nodes.mesh_226.geometry} material={nodes.mesh_226.material} position={[12.825, 1.132, 0.585]} />
        <mesh geometry={nodes.mesh_227.geometry} material={nodes.mesh_227.material} position={[0, 1.078, 6.26]} />
        <mesh geometry={nodes.mesh_228.geometry} material={nodes.mesh_228.material} position={[-14.775, 1.094, -4.165]} />
        <mesh geometry={nodes.mesh_229.geometry} material={nodes.mesh_229.material} position={[14.775, 1.094, -4.165]} />
        <mesh geometry={nodes.mesh_230.geometry} material={nodes.mesh_230.material} position={[-15.634, 0.545, -6.6]} />
        <mesh geometry={nodes.mesh_231.geometry} material={nodes.mesh_231.material} position={[-15.638, 0.545, -6.6]} />
        <mesh geometry={nodes.mesh_232.geometry} material={nodes.mesh_232.material} position={[-15.634, 0.545, -4.3]} />
        <mesh geometry={nodes.mesh_233.geometry} material={nodes.mesh_233.material} position={[-15.638, 0.545, -4.3]} />
        <mesh geometry={nodes.mesh_234.geometry} material={nodes.mesh_234.material} position={[-15.634, 0.545, -2.1]} />
        <mesh geometry={nodes.mesh_235.geometry} material={nodes.mesh_235.material} position={[-15.638, 0.545, -2.1]} />
        <mesh geometry={nodes.mesh_236.geometry} material={nodes.mesh_236.material} position={[-15.634, 0.545, 3.9]} />
        <mesh geometry={nodes.mesh_237.geometry} material={nodes.mesh_237.material} position={[-15.638, 0.545, 3.9]} />
        <mesh geometry={nodes.mesh_238.geometry} material={nodes.mesh_238.material} position={[15.634, 0.545, -5.9]} />
        <mesh geometry={nodes.mesh_239.geometry} material={nodes.mesh_239.material} position={[15.638, 0.545, -5.9]} />
        <mesh geometry={nodes.mesh_240.geometry} material={nodes.mesh_240.material} position={[15.634, 0.545, -3.1]} />
        <mesh geometry={nodes.mesh_241.geometry} material={nodes.mesh_241.material} position={[15.638, 0.545, -3.1]} />
        <mesh geometry={nodes.mesh_242.geometry} material={nodes.mesh_242.material} position={[15.634, 0.545, -0.6]} />
        <mesh geometry={nodes.mesh_243.geometry} material={nodes.mesh_243.material} position={[15.638, 0.545, -0.6]} />
        <mesh geometry={nodes.mesh_244.geometry} material={nodes.mesh_244.material} position={[0, 0.62, 11.49]} />
        <mesh geometry={nodes.mesh_253.geometry} material={nodes.mesh_253.material} position={[0, 1.32, -10.67]} />
        <group position={[-12.98, 1.32, -10.67]}>
          <mesh geometry={nodes.mesh_254.geometry} material={nodes.mesh_254.material} />
          <mesh geometry={nodes.mesh_254_1.geometry} material={nodes.mesh_254_1.material} />
        </group>
        <group position={[12.98, 1.32, -10.67]}>
          <mesh geometry={nodes.mesh_255.geometry} material={nodes.mesh_255.material} />
          <mesh geometry={nodes.mesh_255_1.geometry} material={nodes.mesh_255_1.material} />
        </group>
        <mesh geometry={nodes.mesh_256.geometry} material={nodes.mesh_256.material} position={[-7.7, 1.32, -11.034]} />
        <mesh geometry={nodes.mesh_257.geometry} material={nodes.mesh_257.material} position={[7.7, 1.32, -11.034]} />
      </group>

  );
}

export function Model(props: ThreeElements['group'] & { mode?: SiteMode }) {
  const { nodes } = useGLTF('/channels/oem/macbook-draco.glb') as any;

  
  const isDark = props.mode !== "growth";

  return (
    <group {...props} dispose={null}>
      {!isDark ? <MacbookLight nodes={nodes} /> : <MacbookDark nodes={nodes} />}
    </group>
  );
}

useGLTF.preload('/channels/oem/macbook-draco.glb');
