/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Adapted for UPRAISER Hero — dark: brand gold wire + ghost; light: photo maps.
*/

import { useEffect, useLayoutEffect, useMemo, Suspense } from "react";
import { Center, useGLTF, useTexture } from "@react-three/drei";
import { useFrame, type ThreeElements } from "@react-three/fiber";
import {
  Box3,
  Color,
  LinearSRGBColorSpace,
  LinearMipmapLinearFilter,
  MeshPhysicalMaterial,
  MeshStandardMaterial,
  RepeatWrapping,
  SRGBColorSpace,
  Vector2,
  Vector3,
  type Mesh,
  type Object3D,
  type Texture,
} from "three";
import {
  DRACO_PATH,
  MODEL_URL,
  MODEL_URL_LIGHT,
  SNOW_COLOR_URL,
  SNOW_NORMAL_URL,
  SNOW_ROUGH_URL,
} from "../lib/heroModel";
import { IDLE_BREATHE } from "./hero-terrain/shared";
import { applySnowSparkle } from "./hero-terrain/snowSparkle";
import { heroCapture } from "../lib/heroCapture";

export { DRACO_PATH, MODEL_URL, MODEL_URL_LIGHT } from "../lib/heroModel";
const TERRAIN_SPAN = 420;
/**
 * Planet-curvature radius (world units). Terrain edges bend down like the Earth's
 * horizon, so the map never shows a hard end — edge drop ≈ (span/2)² / (2R) ≈ 48u.
 */
const PLANET_RADIUS = 460;

type EverestGLTF = {
  nodes: {
    Object_4: Mesh;
    Object_5: Mesh;
    Object_6: Mesh;
    Object_7: Mesh;
  };
  materials: {
    Default: MeshStandardMaterial;
  };
  scene: Object3D;
};

type ThemeMode = "light" | "dark";

type EverestProps = ThreeElements["group"] & {
  theme?: ThemeMode;
  castShadow?: boolean;
  receiveShadow?: boolean;
};

function stripMaps(mat: MeshStandardMaterial) {
  mat.map = null;
  mat.normalMap = null;
  mat.roughnessMap = null;
  mat.metalnessMap = null;
  mat.aoMap = null;
  mat.emissiveMap = null;
  mat.alphaMap = null;
  mat.bumpMap = null;
  mat.displacementMap = null;
  mat.needsUpdate = true;
}

function skipRaycast() {}

function sharpenMap(tex: Texture | null) {
  if (!tex) return;
  tex.anisotropy = 16;
  tex.minFilter = LinearMipmapLinearFilter;
  tex.generateMipmaps = true;
  tex.needsUpdate = true;
}

function configureSnowMap(tex: Texture, srgb: boolean) {
  tex.wrapS = RepeatWrapping;
  tex.wrapT = RepeatWrapping;
  tex.anisotropy = 16;
  tex.minFilter = LinearMipmapLinearFilter;
  tex.generateMipmaps = true;
  tex.colorSpace = srgb ? SRGBColorSpace : LinearSRGBColorSpace;
  tex.needsUpdate = true;
}

function SnowSplatBinder({ mat }: { mat: MeshPhysicalMaterial }) {
  const [snowColor, snowNormal, snowRough, rockColor, rockNormal, debrisColor, debrisNormal] = useTexture([
    SNOW_COLOR_URL, SNOW_NORMAL_URL, SNOW_ROUGH_URL, 
    "/rock_color.jpg", "/rock_normal.jpg",
    "/hero/debris/Ground054_1K-JPG_Color.jpg",
    "/hero/debris/Ground054_1K-JPG_NormalGL.jpg"
  ]);

  useLayoutEffect(() => {
    configureSnowMap(snowColor, true);
    configureSnowMap(snowNormal, false);
    configureSnowMap(snowRough, false);
    configureSnowMap(rockColor, true);
    configureSnowMap(rockNormal, false);
    configureSnowMap(debrisColor, true);
    configureSnowMap(debrisNormal, false);
    
    applySnowSparkle(mat, { 
      color: snowColor, 
      normal: snowNormal, 
      rough: snowRough,
      rockColor: rockColor,
      rockNormal: rockNormal,
      debrisColor: debrisColor,
      debrisNormal: debrisNormal
    }, theme === "light");
    mat.needsUpdate = true;
  }, [mat, snowColor, snowNormal, snowRough, rockColor, rockNormal, debrisColor, debrisNormal, theme]);

  return null;
}

function LightSnowMeshes({
  geos,
  src,
  castShadow,
  receiveShadow,
}: {
  geos: Mesh[];
  src: MeshStandardMaterial;
  castShadow: boolean;
  receiveShadow: boolean;
}) {
  const fill = useMemo(() => {
    const mat = new MeshPhysicalMaterial({
      map: src.map,
      normalMap: src.normalMap,
      roughnessMap: src.roughnessMap,
      metalnessMap: src.metalnessMap,
      aoMap: src.aoMap,
      color: new Color("#ffffff"),
      metalness: 0,
      roughness: 0.85, // Подняли базу для большей матовости скал и глубокого снега
      envMapIntensity: 0.15, // Жестко убиваем "софтбокс", тени проваливаются в черноту
      aoMapIntensity: 1.5, // Форсируем микро-тени в трещинах
      clearcoat: 0.0, // Полностью выключаем глянцевый слой
      sheen: 0.0, // Отключаем шелковый блеск
      ior: 1.31,
      specularIntensity: 0.5, // Снижаем общую силу блика
    });
    mat.normalScale = new Vector2(2.0, 2.0); // Разгоняем нормали для колючего микро-рельефа
    sharpenMap(mat.map);
    sharpenMap(mat.normalMap);
    sharpenMap(mat.roughnessMap);
    sharpenMap(mat.aoMap);
    mat.wireframe = false;
    mat.transparent = false;
    mat.opacity = 1;
    mat.depthWrite = true;
    mat.depthTest = true;
    applySnowSparkle(mat, undefined, theme === "light");
    return mat;
  }, [src, theme]);

  useEffect(
    () => () => {
      fill.dispose();
    },
    [fill],
  );

  useFrame(() => {
    const sparkle = fill.userData.uSparkle as { value: number } | undefined;
    if (sparkle) sparkle.value = heroCapture.snap ? 0 : 1;
  });

  return (
    <>
      {geos.map((node, i) => (
        <mesh
          key={`fill-${i}`}
          geometry={node.geometry}
          material={fill}
          castShadow={castShadow}
          receiveShadow={receiveShadow}
          raycast={skipRaycast}
        />
      ))}
      <Suspense fallback={null}>
        <SnowSplatBinder mat={fill} />
      </Suspense>
    </>
  );
}

export function Everest({
  theme = "light",
  castShadow = false,
  receiveShadow = false,
  ...props
}: EverestProps) {
  const isLight = theme === "light";
  const modelUrl = isLight ? MODEL_URL_LIGHT : MODEL_URL;
  const { nodes, materials, scene } = useGLTF(modelUrl, DRACO_PATH) as unknown as EverestGLTF;

  const scale = useMemo(() => {
    const size = new Vector3();
    new Box3().setFromObject(scene).getSize(size);
    const maxDim = Math.max(size.x, size.y, size.z, 0.001);
    return TERRAIN_SPAN / maxDim;
  }, [scene]);

  const geos = useMemo(
    () => [nodes.Object_4, nodes.Object_5, nodes.Object_6, nodes.Object_7],
    [nodes],
  );

  // Dark GLB is pre-bent (scripts/bake-everest-curve.mjs). Light still bends at runtime
  // so photogrammetry tangents stay exact without inflating the 11MB file.
  useMemo(() => {
    if (!isLight) return;
    const box = new Box3();
    for (const node of geos) {
      node.geometry.computeBoundingBox();
      if (node.geometry.boundingBox) box.union(node.geometry.boundingBox);
    }
    const cx = (box.min.x + box.max.x) / 2;
    const cz = (box.min.z + box.max.z) / 2;
    const rLocal = PLANET_RADIUS / Math.max(scale, 1e-6);

    for (const node of geos) {
      const geo = node.geometry;
      if (geo.userData.planetCurved) continue;
      geo.userData.planetCurved = true;

      const pos = geo.attributes.position;
      for (let i = 0; i < pos.count; i += 1) {
        const dx = pos.getX(i) - cx;
        const dz = pos.getZ(i) - cz;
        pos.setY(i, pos.getY(i) - (dx * dx + dz * dz) / (2 * rLocal));
      }
      pos.needsUpdate = true;
      geo.computeVertexNormals();
      // Dark wire has no normal maps — tangents are wasted CPU before the first frame.
      if (isLight && geo.attributes.uv && geo.index) {
        try {
          geo.computeTangents();
        } catch {
          /* non-indexed / incomplete — skip */
        }
      }
      geo.computeBoundingBox();
      geo.computeBoundingSphere();
    }
  }, [geos, scale, isLight]);

  // Dark only — light theme uses photo maps without brand wire overlay.
  const wire = useMemo(() => {
    if (isLight) return null;
    return new MeshStandardMaterial({
      color: new Color("#d4a84a"),
      emissive: new Color("#8a6424"),
      emissiveIntensity: 0.34,
      wireframe: true,
      transparent: true,
      opacity: 0.88,
      metalness: 0.05,
      roughness: 0.68,
      depthWrite: false,
      depthTest: true,
      envMapIntensity: 0,
    });
  }, [isLight]);

  const fill = useMemo(() => {
    if (isLight) return null;

    const mat = materials.Default.clone();
    stripMaps(mat);
    mat.color = new Color("#050504");
    mat.emissive = new Color("#000000");
    mat.emissiveIntensity = 0;
    mat.metalness = 0.02;
    mat.roughness = 0.98;
    mat.envMapIntensity = 0;
    mat.wireframe = false;
    mat.transparent = false;
    mat.opacity = 1;
    mat.depthWrite = true;
    mat.depthTest = true;
    mat.needsUpdate = true;
    return mat;
  }, [materials.Default, isLight]);

  useEffect(
    () => () => {
      wire?.dispose();
      fill?.dispose();
    },
    [wire, fill],
  );

  // Soft idle breathe — mountain scale never pulses. Dark wire only.
  useFrame((state) => {
    if (!wire || heroCapture.snap) return;
    const breathe = Math.sin(state.clock.elapsedTime * IDLE_BREATHE);
    wire.emissiveIntensity = 0.34 + breathe * 0.03;
    wire.opacity = 0.88 + breathe * 0.01;
  });

  return (
    // y compensates <Center> re-centring the bent mesh (edge drop lifts the middle)
    <group {...props} dispose={null} scale={scale} rotation={[0, -0.06, 0]} position={[-6, -34, -22]}>
      <Center>
        {isLight ? (
          <LightSnowMeshes
            geos={geos}
            src={materials.Default}
            castShadow={castShadow}
            receiveShadow={receiveShadow}
          />
        ) : fill ? (
          geos.map((node, i) => (
            <mesh
              key={`fill-${i}`}
              geometry={node.geometry}
              material={fill}
              castShadow={castShadow}
              receiveShadow={receiveShadow}
              raycast={skipRaycast}
            />
          ))
        ) : null}
        {wire
          ? geos.map((node, i) => (
                <mesh
                  key={`wire-${i}`}
                  geometry={node.geometry}
                  material={wire}
                  castShadow={false}
                  receiveShadow={false}
                  raycast={skipRaycast}
                />
            ))
          : null}
      </Center>
    </group>
  );
}

// Preloads owned by HeroTerrainCanvas (active theme first) — avoid parse-time dual fetch.
