/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Adapted for UPRAISER Hero — brand gold wire + warm ghost fill.
GLB is Draco-compressed + texture-stripped (geometry fidelity kept).
*/

import { useMemo } from "react";
import { Center, useGLTF } from "@react-three/drei";
import type { ThreeElements } from "@react-three/fiber";
import { Box3, Color, MeshStandardMaterial, Vector3, type Mesh, type Object3D } from "three";

export const MODEL_URL = "/hero/everest.glb";
/** Local Draco wasm — matches KHR_draco_mesh_compression on the GLB. */
export const DRACO_PATH = "/draco/gltf/";
const TERRAIN_SPAN = 240;

type EverestGLTF = {
  nodes: {
    Object_4: Mesh;
    Object_5: Mesh;
    Object_6: Mesh;
    Object_7: Mesh;
  };
  materials: {
    Default: MeshStandardMaterial;
  };
  scene: Object3D;
};

type ThemeMode = "light" | "dark";

type EverestProps = ThreeElements["group"] & {
  theme?: ThemeMode;
  castShadow?: boolean;
  receiveShadow?: boolean;
};

function stripMaps(mat: MeshStandardMaterial) {
  mat.map = null;
  mat.normalMap = null;
  mat.roughnessMap = null;
  mat.metalnessMap = null;
  mat.aoMap = null;
  mat.emissiveMap = null;
  mat.alphaMap = null;
  mat.bumpMap = null;
  mat.displacementMap = null;
  mat.needsUpdate = true;
}

export function Everest({
  theme = "light",
  castShadow = true,
  receiveShadow = true,
  ...props
}: EverestProps) {
  const { nodes, materials, scene } = useGLTF(MODEL_URL, DRACO_PATH) as unknown as EverestGLTF;
  const isLight = theme === "light";

  const scale = useMemo(() => {
    const size = new Vector3();
    new Box3().setFromObject(scene).getSize(size);
    const maxDim = Math.max(size.x, size.y, size.z, 0.001);
    return TERRAIN_SPAN / maxDim;
  }, [scene]);

  const wire = useMemo(() => {
    const accent = isLight ? "#f8c800" : "#ffcc00";
    return new MeshStandardMaterial({
      color: new Color(accent),
      emissive: new Color(accent),
      emissiveIntensity: isLight ? 0.12 : 0.2,
      wireframe: true,
      transparent: true,
      opacity: isLight ? 0.9 : 0.92,
      metalness: 0.1,
      roughness: 0.4,
      depthWrite: false,
    });
  }, [isLight]);

  const ghost = useMemo(() => {
    const mat = materials.Default.clone();
    stripMaps(mat);
    mat.color = new Color(isLight ? "#eae4da" : "#12100e");
    mat.emissive = new Color("#000000");
    mat.emissiveIntensity = 0;
    mat.metalness = 0.04;
    mat.roughness = 0.94;
    mat.wireframe = false;
    mat.transparent = true;
    mat.opacity = isLight ? 0.7 : 0.55;
    mat.depthWrite = true;
    mat.needsUpdate = true;
    return mat;
  }, [materials.Default, isLight]);

  const geos = useMemo(
    () => [nodes.Object_4, nodes.Object_5, nodes.Object_6, nodes.Object_7],
    [nodes],
  );

  return (
    <group {...props} dispose={null} scale={scale} rotation={[0, 0.22, 0]}>
      <Center>
        {geos.map((node, i) => (
          <mesh
            key={`ghost-${i}`}
            geometry={node.geometry}
            material={ghost}
            castShadow={castShadow}
            receiveShadow={receiveShadow}
          />
        ))}
        {geos.map((node, i) => (
          <mesh
            key={`wire-${i}`}
            geometry={node.geometry}
            material={wire}
            castShadow={false}
            receiveShadow={false}
          />
        ))}
      </Center>
    </group>
  );
}

useGLTF.preload(MODEL_URL, DRACO_PATH);
