/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/channels/oem/tv.glb -o scripts/tv-gltfjsx.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tv.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-1.053, 1.442, 0.785]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Object_3_Plastic_0.geometry} material={materials.Plastic} />
          <mesh geometry={nodes.Object_4_Plastic_0.geometry} material={materials.Plastic} />
          <mesh geometry={nodes.Object_9_Plastic_0.geometry} material={materials.Plastic} />
          <mesh geometry={nodes.Object_10_Plastic_0.geometry} material={materials.Plastic} />
          <mesh geometry={nodes.Object_11_Plastic_0.geometry} material={materials.Plastic} />
          <mesh geometry={nodes.Object_12_Plastic_0.geometry} material={materials.Plastic} />
          <mesh geometry={nodes.Object_13_Plastic_0.geometry} material={materials.Plastic} />
          <mesh geometry={nodes.Object_14_Plastic_0.geometry} material={materials.Plastic} />
          <mesh geometry={nodes.Object_15_Plastic_0.geometry} material={materials.Plastic} />
          <mesh geometry={nodes.Object_16_Plastic_0.geometry} material={materials.Plastic} />
          <mesh geometry={nodes.Object_17_Plastic_0.geometry} material={materials.Plastic} />
          <mesh geometry={nodes.Object_20_Plastic_0.geometry} material={materials.Plastic} />
          <mesh geometry={nodes.Object_21_Plastic_0.geometry} material={materials.Plastic} />
          <mesh geometry={nodes['Object_18_Plastic_(1)_0'].geometry} material={materials.Plastic_1} />
          <mesh geometry={nodes['Object_19_Plastic_(1)_0'].geometry} material={materials.Plastic_1} />
          <mesh geometry={nodes['Object_19_Plastic_(1)_0001'].geometry} material={materials.Plastic_1} />
          <mesh geometry={nodes.Object_22_Custom_0.geometry} material={materials.Custom} />
          <mesh geometry={nodes['Object_1_Custom_(1)_0'].geometry} material={materials.Custom_1} />
          <mesh geometry={nodes['Object_5_Plastic_(2)_0'].geometry} material={materials.Plastic_2} />
          <mesh geometry={nodes['Object_6_Plastic_(2)_0'].geometry} material={materials.Plastic_2} />
          <mesh geometry={nodes['Object_7_Plastic_(2)_0'].geometry} material={materials.Plastic_2} />
          <mesh geometry={nodes['Object_8_Plastic_(2)_0'].geometry} material={materials.Plastic_2} />
          <mesh geometry={nodes.Object_2_Metal_0.geometry} material={materials.Metal} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tv.glb')
